DROP TABLE Branche;

CREATE TABLE IF NOT EXISTS Branche (
	b VARCHAR(10) PRIMARY KEY);
	
INSERT INTO Branche VALUES ('TC');

INSERT INTO Branche VALUES ('HUTECH');

INSERT INTO Branche VALUES ('GB');

INSERT INTO Branche VALUES ('GI');

INSERT INTO Branche VALUES ('GM');

INSERT INTO Branche VALUES ('GP');

INSERT INTO Branche VALUES ('GSM');

INSERT INTO Branche VALUES ('GSU');